/**
 * Map a full-resolution image URL (e.g. `/images/works/beauty-01.webp`)
 * to its 600px thumbnail counterpart (`/images/works/thumbs/beauty-01.webp`).
 *
 * Thumbnails are generated by `scripts/build-thumbs.mjs` and committed
 * to `public/images/works/thumbs/`. They're used on the canvas bento
 * (overview + group view) — the full-res versions stay for the
 * gallery (ExpandedGroup) where the image fills the viewport.
 */
export function thumbSrc(src: string): string {
  return src.replace("/images/works/", "/images/works/thumbs/");
}
