// Generated by scripts/import-text.mjs from /tmp/karim-uploads/02_text/.

export const ARTIST_NAME = "Karim Boumjimar";

export const BIO_SHORT =
  "Karim Boumjimar (b. 1998, Málaga, Spain) is an artist whose work examines social hierarchies through the entanglement of nature, bodies, and identity. Working across drawing, ceramics, and performance, his practice explores how subjectivity is formed through ecological and cultural systems rather than outside of them.";

/**
 * Artist statement, used by AboutView. Compressed from the previous
 * five-paragraph version: paragraph 2 restated the subhead, paragraph
 * 3 doubled paragraph 1's framing, and paragraph 5 was a
 * summary-of-summary. The geography line at the bottom replaces
 * absent context (the previous version omitted that he's based in
 * Copenhagen and is Spanish-Moroccan).
 */
export const ABOUT_PARAGRAPHS = [
  "Karim Boumjimar (b. 1998, Málaga) is a Spanish-Moroccan artist working across drawing, ceramics, and performance. His practice examines social hierarchies through the entanglement of nature, body, and identity, treating subjectivity as something formed through ecological and cultural systems rather than outside of them.",
  "Figures appear hybrid and unstable — simultaneously human, animal, and mythological — emerging through gestural processes that hold transformation over fixity. Compositions are shaped by desire, power, and vulnerability; bodies merge, dissolve, and recombine, refusing the binary categories that fix them.",
  "Ceramics operates at the centre of this language, somewhere between object, body, and residue. Treated as both contemporary and archaeological, it holds traces of movement and memory while remaining open to change.",
  "Boumjimar lives and works in Copenhagen, between Stockholm, Berlin, and Spain.",
];

/**
 * Biographical paragraphs, used by BioView. CV-style.
 */
export const BIO_PARAGRAPHS = [
  "Karim Boumjimar (b. 1998, Málaga) is a Spanish-Moroccan artist working primarily in ceramics, drawing, and performance. He is based between Copenhagen, Stockholm, Berlin, and Spain, following a decade of living and working in London.",
  "He holds an MFA from the Royal Danish Academy of Fine Arts (2025) and a BFA from Central Saint Martins in London. He is self-taught in ceramics, a practice developed through sustained studio work in Copenhagen.",
  "Boumjimar’s recent solo exhibitions include Rites of Affection at Malva Museum, Lahti (2026); Bodies Under Construction at Møstings, Frederiksberg Museums (2026); Birds of Paradise at Viborg Kunsthal (2026); Pandemonium Paradiso at Overgaden Institute of Contemporary Art, Copenhagen (2025); Drawings from the Hotel at Pori Art Museum, Finland (2025); and Deep Cuts at CFHILL, Stockholm (2025).",
  "His work has been exhibited internationally at institutions including Jessica Silverman Gallery (San Francisco), Kuntsi Museum of Modern Art (Vaasa), Liljevalchs Konsthall (Stockholm), Kunsthalle Helsinki, the Miettinen Collection (Berlin), TINA Gallery (London), Kunsthal Charlottenborg (Copenhagen), Centre d’Art la Panera (Lleida), and Schauspielhaus Zürich.",
  "His work is held in collections including the Art Museum of Contemporary Art (AMOCA), Pori Art Museum, the Miettinen Collection, Fondazione Fiera Milano, and the Danish Arts Foundation. He has been featured in Frieze, Kunstkritikk, and Politiken, and was named one of Frieze’s “Ten Artists to Watch” in 2025. His awards include grants from the Danish Arts Foundation (2021–2026), the Carl Nielsen and Anne Marie Carl-Nielsen Foundation (2026), and the Ulrica Hydman Vallien Foundation Talent Award (2025).",
];

/** Inspector default state - uses the artist statement as the canonical bio. */
export const BIO_LONG = ABOUT_PARAGRAPHS;

/** Public collections holding Boumjimar's work. */
export const PUBLIC_COLLECTIONS = [
  "Danish Arts Foundation",
  "Pori Art Museum, Finland",
  "Miettinen Collection, Germany",
  "AMOCA Wales Collection",
  "Fondazione Fiera Milano",
  "Art at Work",
];

/** Recognition / honours. */
export const RECOGNITION = [
  {
    year: "2026",
    text: "Carl Nielsen and Anne Marie Carl-Nielsen Scholarship",
  },
  {
    year: "2026",
    text: "Danish Arts Foundation working grant",
  },
  {
    year: "2025",
    text: "Ulrica Hydman Vallien Foundation Talent Scholarship",
  },
  { year: "2025", text: "Symbiosis received the 2025 Blix Prize" },
  {
    year: "2025",
    text: "Named one of the Ten Artists to Watch in 2025 by Frieze",
  },
];

export const REPRESENTATION = [
  {
    name: "Tina Gallery",
    city: "London",
    url: "https://tinaofficial.co.uk/",
  },
] as const;

export const CONTACT = {
  email: "karim@karimboumjimar.com",
  instagram: "@beigetype",
  instagramUrl: "https://www.instagram.com/beigetype/",
};

export type NewsEntry = {
  date: string;
  text: string;
  url?: string;
};

/** Reverse-chronological. The metadata `date` is the news-publication
 * (or show opening) date; the `text` body collapses duplication by
 * dropping that date and quoting only the closing day where the show
 * runs across multiple months. Exhibition-type descriptors ("solo
 * exhibition" / "group exhibition" / "duo exhibition") are dropped —
 * the section is "News" and the venue tells the rest of the story. */
export const NEWS: NewsEntry[] = [
  {
    date: "19 June 2026",
    text: "Génération Céramique, Fondation d’entreprise Bernardaud, Limoges — through 30 April 2027",
    url: "https://www.bernardaud.com/en/us/news/exposition-generation-ceramique",
  },
  {
    date: "9 June 2026",
    text: "Carl Nielsen and Anne Marie Carl-Nielsen Scholarship; working grant, Danish Arts Foundation",
  },
  {
    date: "10 April 2026",
    text: "Rites of Affection, Malva Museum, Lahti — through 13 September 2026. Film premiere: Traces of Spring.",
    url: "https://malvamuseo.fi/en/exhibitions/karim-boumjimar-rites-of-affection/",
  },
  {
    date: "28 March 2026",
    text: "Bodies Under Construction, Møstings, Frederiksberg Museums — through 7 June 2026",
    url: "https://frederiksbergmuseerne.dk/en/udstillinger/karim-boumjimar/",
  },
  {
    date: "8 March 2026",
    text: "I Can Buy Myself Flowers, Kunsthal N — through 2 August 2026",
    url: "https://kunsthaln.dk/en/udstilling/i-can-buy-myself-flowers/",
  },
  {
    date: "5 March 2026",
    text: "Beauty is the Best Defense, Jessica Silverman Gallery, San Francisco — through 11 April 2026",
    url: "https://jessicasilvermangallery.com/online-shows/beauty-is-the-best-defense-ovr/",
  },
  {
    date: "5 February 2026",
    text: "Featured in Politiken",
    url: "https://politiken.dk/ibyen/art10617381/%C2%BBDer-er-ikke-s%C3%A5-meget-jeg-f%C3%B8ler-jeg-g%C3%A5r-glip-af.-Jo-m%C3%A5ske-lige-et-par-n%C3%A6tter-mere-p%C3%A5-Berghain%C2%AB",
  },
  {
    date: "24 January 2026",
    text: "Body Politics, Kuntsi Museum of Modern Art, Vaasa — through 4 April 2026",
    url: "https://vaasa.fi/koe-ja-nae/kulttuuria-vaasassa-ja-seudulla/vaasan-museot/nayttelyt-ja-tapahtumat/miettinen-collection-body-politics/",
  },
  {
    date: "23 January 2026",
    text: "Birds of Paradise, Viborg Kunsthal — through 10 May 2026",
    url: "https://artviewer.org/karim-boumjimar-at-viborg-kunsthal/",
  },
  {
    date: "18 December 2025",
    text: "Featured in Cultbytes",
    url: "https://cultbytes.com/in-stockholm-karim-boumjimars-insistence-on-mutability-is-defiant/",
  },
  {
    date: "10 December 2025",
    text: "Featured in Dagens Industri Weekend",
    url: "https://www.di.se/nyheter/mestadels-formogna-som-koper-mina-verk/",
  },
  {
    date: "21 November 2025",
    text: "Ulrica Hydman Vallien Foundation Talent Scholarship",
    url: "https://www.ulricahydmanvalliensstiftelse.se/the-scholarships/",
  },
  {
    date: "21 November 2025",
    text: "Stockholm Cosmologies, Liljevalchs Konsthall, Stockholm — through 11 January 2026",
    url: "https://liljevalchs.se/en/kalender/stockholm-cosmologies/",
  },
  {
    date: "14 November 2025",
    text: "Deep Cuts, CFHILL, Stockholm — through 30 December 2025",
    url: "https://www.contemporaryartlibrary.org/project/karim-boumjimar-61510",
  },
  {
    date: "1 November 2025",
    text: "I Will Look Into the Earth, Kunsthalle Helsinki — through 11 January 2026",
    url: "https://taidehalli.fi/en/events/i-will-look-into-the-earth/",
  },
  {
    date: "18 October 2025",
    text: "This Is Just the Beginning, Miettinen Collection, Berlin — through 31 December 2025",
    url: "https://miettinen-collection.de/2025/10/26/this-is-just-the-beginning/",
  },
  {
    date: "9 October 2025",
    text: "Mouths, Vessels, Portals, Alice Folker Gallery, Copenhagen — through 28 November 2025",
    url: "https://alicefolker.dk/exhibitions/7-karim-boumjimar-mouths-vessels-portals/",
  },
  {
    date: "29 August 2025",
    text: "Pandemonium Paradiso, O—Overgaden, Copenhagen — through 26 October 2025",
    url: "https://artviewer.org/karim-boumjimar-at-o-overgaden-copenhagen/",
  },
  {
    date: "27 June 2025",
    text: "Featured in ELLE Danmark",
    url: "https://elle.dk/agenda/karriere/billedkunstner-karim-boumjimar-at-springe-ud-som-kunstner-var-i-virkeligheden-svaerere-end-at-springe-ud-som-queer/",
  },
  {
    date: "20 June 2025",
    text: "When Form Becomes Attitude, Robert Grunenberg, Berlin — through 9 August 2025",
    url: "https://robertgrunenberg.com/exhibition/when-form-becomes-attitude/",
  },
  {
    date: "17 May 2025",
    text: "Drawings from the Hotel, Pori Art Museum — through 6 July 2025",
    url: "https://www.poriartmuseum.fi/en/events/karim-boumjimar-drawings-from-the-hotel-2/",
  },
  {
    date: "11 April 2025",
    text: "Symbiosis received the 2025 Blix Prize, Kunsthal Charlottenborg",
  },
  {
    date: "4 April 2025",
    text: "MiArt, Milan — participation 4 April 2025 – 6 April 2025",
  },
  {
    date: "6 February 2025",
    text: "Charlottenborg Spring Exhibition, Kunsthal Charlottenborg — through 9 March 2025",
    url: "https://artmap.com/kunsthalcharlottenborg/exhibition/charlottenborg-spring-exhibition-2025",
  },
  {
    date: "17 January 2025",
    text: "Kultuur, TINA Gallery, London — through 1 March 2025",
    url: "https://saliva.live/exhibitions/66c4dd65",
  },
  {
    date: "7 January 2025",
    text: "Named one of Frieze “Ten Artists to Watch in 2025”",
    url: "https://www.frieze.com/article/ten-artists-watch-2025",
  },
  {
    date: "11 November 2024",
    text: "Featured in Politiken",
    url: "https://politiken.dk/kultur/design/art10131168/%C2%BBHun-stod-og-peb-s%C3%A5-jeg-hev-hende-op-i-sengen.-Det-skulle-jeg-nok-ikke-have-gjort%C2%AB",
  },
  {
    date: "28 October 2023",
    text: "Queer Ecologies: Naturally Subversive Aberrations, Centre d’Art la Panera, Lleida — through 28 January 2024",
    url: "https://www.lapanera.cat/en/programming/expositions/ecologies-queer-aberracions-naturalment-subversives",
  },
  {
    date: "4 May 2023",
    text: "Fear and Fauna, ARIEL – Feminism in the Aesthetic — through 18 June 2023",
    url: "https://arielfeminisms.dk/#upcoming-fear-and-fauna",
  },
  {
    date: "13 August 2021",
    text: "Psychopathia Sexualis, O—Overgaden, Copenhagen — through 10 October 2021",
    url: "https://overgaden.org/en/exhibitions/psychopathia-sexualis",
  },
];

export type ExhibitionEntry = {
  year: string;
  title: string;
  venue: string;
  city?: string;
  date?: string;
  type?: "solo" | "group" | "duo" | "performance";
};

export const EXHIBITIONS: ExhibitionEntry[] = [];

export const GRANT_INFO = {
  title: "Working-Class Creative Grant",
  intro:
    "A one-off 500 Euro grant awarded throughout the year to a different working-class creative anywhere in the world, funded through art sales.",
  body: [
    "The grant targets individuals who receive little or no institutional support and who would benefit from practical financial assistance. Recipients can use funds flexibly - for materials, equipment, research, travel, studio costs, or living expenses.",
    "There are no strings attached and no expectation of exchange. Applications remain in consideration indefinitely with rolling reviews throughout the year and no fixed deadline.",
    "Previous recipients (2025-2026) include artists and organizations working in visual arts, photography, and community services across international locations.",
  ],
  applyEmail: "karim@karimboumjimar.com",
  applySubject: "Grant: Your Name",
  applyChecklist: [
    "Brief personal introduction",
    "Work sample or description of interests / situation",
    "Contact information",
  ],
};
